name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installation des dépendances
        run: |
          cd backend
          npm install

      - name: Lancement des tests
        run: |
          cd backend
          npm test

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v3

      - name: Connexion à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build de l’image Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/user-management-backend ./backend

      - name: Push de l’image vers Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/user-management-backend
